# Generated by Django 4.1.6 on 2023-02-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_rename_end_users_memory_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': 'memories'},
        ),
    ]
