# Generated by Django 4.1.6 on 2023-02-11 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_alter_memory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memory',
            name='img_url',
            field=models.ImageField(upload_to='local_uploads/'),
        ),
    ]
