# Generated by Django 4.1.6 on 2023-02-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_memory_visited_at_alter_memory_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='visited_at',
            field=models.DateField(),
        ),
    ]
