# Generated by Django 4.1.6 on 2023-02-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_alter_memory_visited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='img_url',
            field=models.FileField(upload_to='local_uploads/'),
        ),
    ]
