# Generated by Django 4.1.6 on 2023-02-11 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_alter_memory_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='img_url',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='local_uploads/', verbose_name='Images')),
                ('memory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.memory')),
            ],
        ),
    ]
