# Generated by Django 4.1.6 on 2023-02-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0007_remove_memory_img_url_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img_url',
            field=models.TextField(),
        ),
    ]
