# Generated by Django 4.1.6 on 2023-02-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0010_memory_lat_memory_lng_alter_images_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img_url',
            field=models.TextField(),
        ),
    ]
